# Read the docs config, for documentation see:
# https://docs.readthedocs.io/en/stable/config-file/v2.html#python
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  apt_packages:
    - openslide-tools
    - libopenjp2-7-dev
python:
  version: "3.8"
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
sphinx:
  configuration: docs/conf.py
